vue-macros/vue-macros

- packages/macros/src/define-model/transform.ts
- packages/macros/tests/__snapshots__/define-model.test.ts.snap
- packages/macros/tests/__snapshots__/rollup.test.ts.snap
- packages/macros/tests/fixtures/define-model/vue2-custom-vmodel-defineComponent.vue
- packages/macros/tests/fixtures/define-model/vue2-custom-vmodel.vue
- packages/macros/tests/fixtures/mixed-vue2-model.vue
- packages/macros/tests/rollup.test.ts
add vue2 [Customizing-Component-v-model](https://v2.vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model)
[Example](https://codesandbox.io/s/red-sea-ycblru)
How to test `defineOptions` and `defineModel` together? 😢
> feat(macros): supports customizing v-model in Vue 2

- docs/.vitepress/configs/pwa.ts
This PR,
- added caching for `https://contrib.rocks/*`.
- disable service worker in `dev` mode to fix dev reloading.
- remove `maxEntries` for image cache.
> feat(docs): optimize PWA cache

- .changeset/strong-mirrors-roll.md
- packages/volar/src/define-slots.ts
When using the defineSlots plugin in a project that includes components with no `<script setup>`, the plugin generates an errors because `sfc.scriptSetupAst` is `undefined` (the previous `sfc.scriptSetupAst!` is wrong as this is not guaranteed).
Logged error:
```
/project/node_modules/.pnpm/@vue-macros+volar@0.5.0_vue-tsc@1.0.9+vue@3.2.41/node_modules/@vue-macros/volar/dist/define-slots.js:52
return sourceFile.forEachChild((node) => {
^
TypeError: Cannot read properties of undefined (reading 'forEachChild')
at getTypeArg (/project/node_modules/.pnpm/@vue-macros+volar@0.5.0_vue-tsc@1.0.9+vue@3.2.41/node_modules/@vue-macros/volar/dist/define-slots.js:52:21)
at Object.resolveEmbeddedFile (/project/node_modules/.pnpm/@vue-macros+volar@0.5.0_vue-tsc@1.0.9+vue@3.2.41/node_modules/@vue-macros/vol …
```
> fix(volar): defineSlots without `<script setup>`

- .changeset/sour-toes-sit.md
- packages/short-emits/package.json
Macros.d.ts and macros-global.d.ts are missing in short-emits module. This PR is just to fix this.
> fix(short-emits): add dts to pkg files

- .changeset/silver-ladybugs-mix.md
- packages/common/src/vue.ts
Stricter types
none
I also noticed the functions below as declared as `const ... () => ` instead of `function ...() ` while in other parts of the codebase the `function` syntax is used. It might be worth using the same `function` syntax in both places for consistency and discoverability in the project
> refactor(common): use getters in SFC

- .changeset/perfect-nails-flow.md
- packages/api/src/ts.ts
- packages/better-define/tests/__snapshots__/fixtures.test.ts.snap
- packages/better-define/tests/fixtures.test.ts
- packages/better-define/tests/fixtures/export-type-normal.exclude.vue
- packages/better-define/tests/fixtures/export-type.exclude.vue
- packages/better-define/tests/fixtures/import-from-vue.vue
- packages/common/src/vue.ts
Extract `setupScript` content if they import type from `vue` file.
closes #208
> fix(better-define): cannot import type from vue file

- docs/zh-CN/macros/index.md
When reading the Chinese document, I found that in [Pages with errors](https://vue-macros.sxzz.moe/zh-CN/macros) this page click `definePropsRefs` is directly jumped to the English document, can not jump to the Chinese document, seems to be a path error, I will modify its path
> docs: correct link path

- .changeset/rotten-eagles-lick.md
- .changeset/tender-cheetahs-accept.md
- packages/better-define/src/index.ts
- packages/common/src/constants.ts
- packages/define-emit/src/index.ts
- packages/define-models/src/index.ts
- packages/define-options/src/index.ts
- packages/define-prop/src/index.ts
- packages/define-props-refs/src/index.ts
- packages/define-props/src/index.ts
- packages/define-slots/src/index.ts
- packages/export-props/src/index.ts
- packages/hoist-static/src/index.ts
- packages/reactivity-transform/src/index.ts
Improve auto import for project with `@vue/cli-service@5` with Vue3.
I used `unplugin-vue-define-options@1.3.3` in my project, and I need to specific the include option in my `vue.config.js` file.
```ts
UnpluginDefineOptions({ version: 3, include: [/\.setup\.[cm]?[jt]sx?$/, /\.vue$/, /\.vue\?vue&/] })
```
Just remove original Vue version 2 limited to include origin reg `REGEX_VUE_SUB` as default can solve this problem.
close #327 
Reproduction link https://stackblitz.com/edit/vitejs-vite-drvu4g?file=src/App.vue
> fix: include regex

- docs/.vitepress/locales/common.ts
- docs/features/export-expose.md
- docs/zh-CN/features/export-expose.md
> docs: add `exportExpose` docs

- .changeset/fair-planes-pay.md
- packages/chain-call/macros.d.ts
- packages/chain-call/package.json
- packages/chain-call/src/api.ts
- packages/chain-call/src/core/index.ts
- packages/chain-call/src/esbuild.ts
- packages/chain-call/src/index.ts
- packages/chain-call/src/rollup.ts
- packages/chain-call/src/vite.ts
- packages/chain-call/src/webpack.ts
- packages/chain-call/tests/__snapshots__/fixtures.test.ts.snap
- packages/chain-call/tests/fixtures.test.ts
- packages/chain-call/tests/fixtures/basic.vue
- packages/chain-call/tests/fixtures/declare.vue
- packages/chain-call/tests/fixtures/destruct.vue
- packages/chain-call/tests/fixtures/empty-defaults.vue
- packages/chain-call/tests/fixtures/empty.vue
- packages/chain-call/tests/fixtures/tsx.vue
- packages/chain-call/tsup.config.ts
- packages/chain-call/vue2-macros.d.ts
- packages/common/package.json
- packages/common/src/vue.ts
- packages/define-props-refs/macros-global.d.ts
- packages/define-props-refs/tests/__snapshots__/fixtures.test.ts.snap
- packages/define-props-refs/vue2-macros.d.ts
- packages/macros/macros.d.ts
- packages/macros/package.json
- packages/macros/src/index.ts
- packages/macros/vue2-macros.d.ts
- pnpm-lock.yaml
Extends `defineProps`, support call `withDefaults` as a chain:
```vue
<script setup lang="ts">
import { defineProps } from 'unplugin-vue-macros/macros' assert { type: 'macro' }
const { foo } = defineProps<{
foo?: string
}>().withDefaults({
foo: '111',
})
</script>
<template></template>
```
will compiles to
```vue
<script setup lang="ts">
const { foo } = withDefaults(defineProps<{
foo?: string
}>(), {
foo: '111'
})
</script>
<template></template>
```
closes #214
> feat: chain call

- .changeset/rich-cobras-marry.md
- packages/define-prop/src/core/index.ts
- playground/vue3/src/examples/define-prop/child.vue
closed #479
``` ts
const props = $(definePropsRefs(['msg'])) 
```
> fix(define-prop): transform correct call expression

- .changeset/healthy-ways-wave.md
- packages/volar/src/define-slots.ts
> /var __VLS_slots!: .*/
> /var __VLS_slots!: [\S\s]*?;/
> fix(volar/define-slots): regular expression error

- .changeset/short-pens-study.md
- docs/guide/bundler-integration.md
- docs/zh-CN/guide/bundler-integration.md
- packages/volar/src/setup-jsdoc.ts
- playground/vue3/src/examples/setup-jsdoc/button.vue
- playground/vue3/src/examples/setup-jsdoc/export-render/index.vue
- playground/vue3/src/examples/setup-jsdoc/index.vue
- playground/vue3/tsconfig.json
With this plugin, you can write jsDoc in front of the first line or 'export default' in <script setup>.
``` ts
// tsconfig.json
{
"vueCompilerOptions": {
"plugins": [
"@vue-macros/volar/setup-jsdoc"
],
}
}
```
``` vue
<script setup lang="tsx">
/**
* # My Button Component
* To trigger an operation.
*
* @deprecated Please use `MyButtonV2` instead.
*
* @example
* ```vue
* <MyButton>Click Me</MyButton>
* ```
*/
defineRender(() => <button />)
</script>
```
Or before of `export default`
``` vue
<script setup lang="tsx">
import { Ok } from '../../../assert'
/**
* # ExportRender
* Transform `default export` to defineRender.
*
* @deprecated Please use `ExportRenderV2` instead.
*
* @example
* ```vue
* <ExportRender />
* ```
*/
export default () => <Ok />
</script>
```
> feat(volar): introduce `setupJsdoc`

- .changeset/many-parrots-serve.md
- docs/macros/define-slots.md
- docs/zh-CN/macros/define-slots.md
- packages/volar/src/define-slots.ts
- packages/volar/src/jsx-directive.ts
- playground/vue2/src/examples/define-slots/child.vue
- playground/vue2/src/examples/define-slots/parent.vue
- playground/vue2/src/examples/jsx-directive/v-slot/child.vue
- playground/vue2/src/examples/jsx-directive/v-slot/index.vue
- playground/vue3/src/examples/define-slots/child.vue
- playground/vue3/src/examples/define-slots/parent.vue
> feat(volar): support defineSlots for vue2

- .changeset/thick-crews-begin.md
- packages/jsx-directive/src/core/v-if.ts
- packages/jsx-directive/tests/__snapshots__/v-if.test.ts.snap
- packages/jsx-directive/tests/fixtures/v-if/v-if.vue
- packages/volar/src/jsx-directive.ts
``` tsx
<div v-if={foo === 0}>0</div>
// Transform to
{(foo === 1) ? <div>1</div> : null}
```
> fix(jsx-directive): add bracket for ternary expression in v-if

- .changeset/dirty-cats-repeat.md
- packages/volar/src/jsx-directive.ts
- playground/vue3/src/examples/jsx-directive/v-slot/index.vue
> fix(volar/jsx-directive): allow v-slot:default in template tag

- .changeset/rotten-buckets-agree.md
- packages/setup-block/src/core/index.ts
Context: https://github.com/vuejs/core/pull/9674
- `TextModes` type and `getTextModes` option are removed in 3.4
- To get equivalent behavior, use the new option `parseMode: 'sfc'`
Since `getTextModes` is ignored in 3.4 and `parseMode` is ignored in 3.3, this should work for both versions.
> feat: compat for Vue 3.4

- packages/volar/src/jsx-directive/index.ts
- packages/volar/src/jsx-directive/v-model.ts
Support incorrect jsx-directive for `v-mode:`
> fix(volar/jsx-directive): support v-model with no argument

- tsconfig.base.json
global JSX types are removed in 3.4.
> chore: set jsxImportSource in tsconfig for Vue 3.4

- .changeset/unlucky-planes-watch.md
- packages/reactivity-transform/src/core/transform.ts
- packages/reactivity-transform/tests/__snapshots__/fixtures.test.ts.snap
- packages/reactivity-transform/tests/fixtures/vue3/issue-608.vue
Currently, `reactivity-transform` doesn't correctly pop the scope stack when encountering a `CatchClause`. This causes it to get stuck in an incorrect scope, leading to confusing/wrong behaviour.
* [Here](https://github.com/vue-macros/vue-macros/blob/501fad4df5cc77f4c6e5c54afc122dba659b86c3/packages/reactivity-transform/src/core/transform.ts#L662)'s where the catch clause is pushed onto the stack
* ...but it's not checked for [here](https://github.com/vue-macros/vue-macros/blob/501fad4df5cc77f4c6e5c54afc122dba659b86c3/packages/reactivity-transform/src/core/transform.ts#L751).
```js
let ref = $ref("value");
console.log(isRef(ref)); // -> false
try {}
catch {
const ref = "";
}
console.log(isRef(ref)); // -> true
```
> fix(reactivity-transform): `catch` scope

- .changeset/rare-trainers-fetch.md
- packages/jsx-directive/src/core/v-slot.ts
- packages/volar/src/jsx-directive/v-slot.ts
> fix(jsx-directive): v-slot and v-else-if co-usage

- .changeset/shiny-falcons-develop.md
- packages/volar/src/jsx-directive/index.ts
- packages/volar/src/jsx-directive/v-for.ts
- packages/volar/src/jsx-directive/v-if.ts
- packages/volar/src/jsx-directive/v-slot.ts
> refactor(volar/jsx-directive): use getStart instead of pos

- .changeset/stupid-flowers-dance.md
- docs/features/jsx-directive.md
- docs/zh-CN/features/jsx-directive.md
- packages/jsx-directive/src/core/index.ts
- packages/jsx-directive/src/core/v-for.ts
- packages/jsx-directive/src/core/v-slot.ts
- packages/jsx-directive/tests/__snapshots__/v-for.test.ts.snap
- packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
- packages/jsx-directive/tests/fixtures/v-for/v-for.vue
- packages/jsx-directive/tests/fixtures/v-slot/index.vue
- packages/jsx-directive/tests/v-for.test.ts
- packages/volar/src/jsx-directive/index.ts
- packages/volar/src/jsx-directive/v-for.ts
- packages/volar/src/jsx-directive/v-if.ts
- packages/volar/src/jsx-directive/v-slot.ts
- playground/vue3/src/examples/jsx-directive/v-slot/child.vue
- playground/vue3/src/examples/jsx-directive/v-slot/index.vue
```tsx
<Comp>
<template v-for={(Slot, slotName) in slots} v-slot:$slotName$={scope}>
<Slot {...scope} />
</template>
</Comp>
```
> feat(jsx-directive/v-slot): support dynamic argument

- .changeset/perfect-trains-design.md
- packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
- packages/jsx-directive/tests/fixtures/v-slot/index.vue
- packages/volar/src/jsx-directive/context.ts
- packages/volar/src/jsx-directive/index.ts
- packages/volar/src/jsx-directive/ref.ts
- playground/vue3/src/examples/jsx-directive/v-slot/index.vue
> feat(volar/jsx-directive): add type to the functional template-ref

- .changeset/loud-laws-drop.md
- packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
- packages/jsx-directive/tests/fixtures/v-slot/index.vue
- packages/volar/src/jsx-directive/v-slot.ts
> fix(volar/jsx-directive): v-if and v-slot co-usage

- docs/macros/define-prop.md
- docs/zh-CN/macros/define-prop.md
- packages/volar/src/define-prop.ts
> fix(volar/define-prop): $defineProp and defineSlots co-usage

- .changeset/famous-houses-melt.md
- docs/features/boolean-prop.md
- docs/zh-CN/features/boolean-prop.md
- packages/boolean-prop/src/core/transformer.ts
- packages/boolean-prop/tests/__snapshots__/compiler.test.ts.snap
- packages/boolean-prop/tests/compiler.test.ts
This PR introduce a short false prop for `booleanProp` macros.
```
<Comp !checked /> 
```
Will be convert to:
```
<Comp :checked="false" />
```
And the "!" prefix can be custom too.
By the way, I think the `Convert <Comp checked /> to <Comp :checked="true" /> maros` should be removed, It's vue's default behavior, right?
> feat(boolean-prop): add support for negative prefix as false value

- packages/macros/tests/__snapshots__/fixtures.test.ts.snap
- pnpm-lock.yaml
- pnpm-workspace.yaml
To make ecosystem-ci pass: https://github.com/vuejs/ecosystem-ci/actions/runs/10702172980/job/29669763309
Edit: I realized this also need to bump Vue to 3.5.2 after it's released.
> chore: upgrade vue to 3.5.2

- .changeset/two-poems-jump.md
- packages/volar/src/jsx-directive/index.ts
- packages/volar/src/jsx-directive/v-bind.ts
Vue components can accept intrinsic attributes such as `aria-*` or `data-*`. The current implementation transforms all attributes with a `-` character. We should ignore any attributes for v-bind if they don't contain `_` as the purpose of the transformation is to support modifiers.
> fix(volar/jsx-directive): incorrect transformation of intrinsic attributes

- .changeset/silent-spies-bathe.md
- packages/volar/src/common.ts
The pathsBasePath will be undefined when paths unset in tsconfig.
> fix(volar): use configFilePath instead of pathsBasePath

- .changeset/new-dodos-kiss.md
- packages/volar/src/jsx-directive/ref.ts
- playground/vue3/src/examples/jsx-ref/index.vue
```tsx
<Comp
{...{ref: ... } as any}
foo={foo} // <= will be never expose error
/>
```
> fix(volar/jsx-directive): use object instead of any

- .changeset/big-comics-exercise.md
- packages/volar/src/jsx-directive/v-model.ts
> fix(volar/jsx-directive): use props instead of emits for inferred required type in v-model

- .changeset/chilly-toes-give.md
- packages/volar/src/jsx-directive/custom-directive.ts
use getStart instead of node.getStart to prevent vue-tsc error
> fix(volar/jsx-directive): use getStart instead of node.getStart to prevent vue-tsc error

- .changeset/shiny-cobras-hope.md
- packages/jsx-directive/package.json
- packages/jsx-directive/src/core/restructure/index.ts
- pnpm-lock.yaml
compiler-core's walkIdentifiers don't support browser, so use compiler-sfc instead.
> fix(jsx-directive): use compiler-sfc instead of compiler-core to expose walkIdentifiers

- packages/volar/src/jsx-directive/index.ts
- packages/volar/src/jsx-directive/v-for.ts
- packages/volar/src/jsx-directive/v-slot.ts
> fix(volar/jsx-directive): prevent missing types when v-slots are used with v-for

- docs/.vitepress/config/index.ts
- docs/vite.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Thanks for using my plugin 🤝
But I noticed a problem in the commit https://github.com/vue-macros/vue-macros/commit/d25754ee06572d08fd1dfb6103affe5a4b229c40
@sxzz you added the plugin to the **Vite** configuration, but it needs to be added to the **VitePress** configuration (`.vitepress/config/index.ts`) for it to work correctly
I excluded the Chinese version of the documentation for LLMs (and why have LLM documentation in two languages ​​if you can leave only English?) and some extra files
Now the documentation is generated correctly and only in English
> fix: fix `llms.txt` generation

- packages/nuxt/package.json
- packages/nuxt/src/index.ts
- packages/nuxt/src/volar.ts
Issues #948 and #956: The Volar plugin does not work when only `@vue-macros/nuxt` is installed.
Since Volar plugin config of  `.nuxt/tsconfig.json` is `vue-macros/volar`, `@vue/language-tools` does not read it's path correctly when vue-macros is not installed.
```json
{
"vueCompilerOptions": {
"plugins": [
"vue-macros/volar"
]
}
}
```
So i expose a Volar plugin for package.json, and use `@vue-macros/nuxt/volar` instead `vue-macros/volar` to resolve it.
```json
{
"vueCompilerOptions": {
"plugins": [
"@vue-macros/nuxt/volar"
]
}
}
```
> feat(nuxt): expose volar plugin

- packages/volar/src/common.ts
- packages/volar/src/define-emit.ts
- packages/volar/src/define-generic.ts
- packages/volar/src/define-models.ts
- packages/volar/src/define-prop.ts
- packages/volar/src/export-expose.ts
- packages/volar/src/export-props.ts
- packages/volar/src/export-render.ts
- packages/volar/src/jsx-directive/context.ts
- packages/volar/src/jsx-directive/custom-directive.ts
- packages/volar/src/jsx-directive/index.ts
- packages/volar/src/jsx-directive/ref.ts
- packages/volar/src/jsx-directive/v-bind.ts
- packages/volar/src/jsx-directive/v-for.ts
- packages/volar/src/jsx-directive/v-if.ts
- packages/volar/src/jsx-directive/v-model.ts
- packages/volar/src/jsx-directive/v-on.ts
- packages/volar/src/jsx-directive/v-slot.ts
- packages/volar/src/jsx-ref.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
1. Remove `getStart` and `getEnd` utils, use ts-macro instead.
2. Eliminate the mental burden of not having a related AST util when using vue-tsc. https://github.com/ts-macro/ts-macro/commit/3946bc951d431689632fdb844742ceb8277241ca
> refactor(volar):  upgrade ts-macro to 0.2.7

- packages/define-render/src/core/index.ts
```vue
<script vapor lang="tsx">
// in vapor component should't wrapped by function.
defineRender(<div>foo</div>)
</script>
```
> feat(define-render): auto infer vapor mode
