vue-macros/vue-macros

README-zh-CN.md
README.md

This PR fixes a typo in README

chore: fix typo in README

---

README-zh-CN.md

chore: fix typo

---

README-zh-CN.md

docs: sync zh-CN with en

---

packages/define-options/README-zh-CN.md

update Chinese document of define-options
> "0.8.0" 在 vite中存在相同问题， 回退到"0.7.3"版本正常

docs(define-options): update dts path

---

.changeset/heavy-glasses-impress.md
.gitignore
packages/setup-component/src/core/constants.ts
packages/setup-component/src/core/index.ts
packages/setup-component/src/core/sub-module.ts
packages/setup-component/src/index.ts
packages/setup-component/tests/__snapshots__/setup-component.test.ts.snap
packages/setup-component/tests/fixtures/SetupFC.tsx
packages/setup-component/tests/fixtures/return-render.tsx
playground/src/App.vue
playground/src/demo/foo.ts
playground/src/demo/full.setup.tsx
playground/src/demo/setup-fc.type.tsx

this pr can solve incorrectly resolve import statements in `defineSetupComponent` `SetupFC<Props, Emits>` in beta version
https://github.com/sxzz/unplugin-vue-macros/issues/75

feat(setup-component): support resolve import statements

---

docs/.vitepress/config.ts

Because there is no `docs` dictionary in `docs` package, so edit pattern need change

fix(docs): edit link err

---

docs/macros/index.md

Improve experimental warning's appearance.
Difference between old and new，the below one is new.👇🏻
Dark Mode not change.

feat(docs): improve experimental warning appearance

---

docs/macros/short-vmodel.md

fix the docs: the $ should be *
None
No

docs: fix typo

---

README-zh-CN.md

docs: fix translation

---

.changeset/chatty-schools-sin.md
.github/renovate.json5
docs/package.json
packages/define-model/package.json
packages/define-options/package.json
packages/define-render/package.json
packages/define-slots/package.json
packages/hoist-static/package.json
packages/macros/package.json
packages/macros/src/index.ts
packages/named-template/package.json
packages/setup-component/package.json
packages/setup-sfc/package.json
packages/short-emits/package.json
playground/vue2/package.json
playground/vue3/package.json
pnpm-lock.yaml

feat: upgrade unplugin

---

packages/define-render/src/core/index.ts
packages/define-render/src/index.ts

fix(define-render): typo of `transformDefineRender`

---

docs/macros/define-options.md

docs: add `unplugin-vue-define-options` ts support

---

docs/macros/define-slots.md

docs: typo

---

.changeset/silent-items-poke.md
packages/define-model/src/core/index.ts
packages/define-props/src/core/index.ts
packages/define-props/src/index.ts
packages/define-props/tests/fixtures.test.ts
packages/define-slots/src/core/index.ts
packages/define-slots/src/index.ts
packages/define-slots/tests/fixtures.test.ts
packages/export-props/src/core/index.ts
packages/export-props/src/index.ts
packages/export-props/tests/fixtures.test.ts
packages/reactivity-transform-vue2/src/core/index.ts
packages/reactivity-transform-vue2/src/index.ts
packages/setup-sfc/src/core/index.ts
packages/setup-sfc/src/index.ts

fix spell error 
`transfrom` -> `transform`

fix(typo): transfrom -> transform

---

docs/macros/index.md

add the definePropsRefs into api list

fix: add the definePropsRefs into api list

---

docs/.vitepress/locales/en.ts
docs/.vitepress/locales/zh-cn.ts

add activeMatch in nav config，it can highlight the nav text although sideNav not in the first title

docs: add activeMatch

---

docs/macros/define-prop.md

docs: fix description of boolean

---

docs/.vitepress/locales/common.ts
docs/features/export-props.md
docs/macros/chain-call.md
docs/macros/index.md
docs/zh-CN/macros/chain-call.md
docs/zh-CN/macros/index.md

docs: add chain-call

---

.changeset/heavy-eyes-rescue.md
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-if.ts
packages/jsx-directive/tests/__snapshots__/v-for.test.ts.snap
packages/jsx-directive/tests/__snapshots__/v-if.test.ts.snap
packages/volar/src/jsx-directive.ts

refactor(jsx-directive): use null instead of empty string

---

.changeset/large-mails-decide.md
packages/jsx-directive/src/core/index.ts

fix(jsx-directive): use continue

---

.changeset/chatty-pillows-type.md
docs/features/jsx-directive.md
docs/zh-CN/features/jsx-directive.md
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-memo.ts
packages/jsx-directive/tests/__snapshots__/v-for.test.ts.snap
packages/jsx-directive/tests/__snapshots__/v-memo.test.ts.snap
packages/jsx-directive/tests/fixtures/v-memo/v-memo.tsx
packages/jsx-directive/tests/fixtures/v-memo/v-memo.vue
packages/jsx-directive/tests/fixtures/v-memo/v-once.tsx
packages/jsx-directive/tests/fixtures/v-memo/v-once.vue
packages/jsx-directive/tests/v-memo.test.ts
playground/vue3/src/examples/jsx-directive/index.vue
playground/vue3/src/examples/jsx-directive/v-memo.vue

``` tsx
// v-memo
<div
v-for={i in list}
v-memo={[selected === i]}
key={i}
onClick={() => (selected = i)}
>
{i}: {selected}
</div>
// v-once
<div v-once>{selected}</div>
```

feat(jsx-directive): add v-memo & v-once directive

---

.changeset/modern-teachers-think.md
docs/features/jsx-directive.md
docs/zh-CN/features/jsx-directive.md
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/v-html.ts
packages/jsx-directive/src/index.ts
packages/jsx-directive/tests/__snapshots__/v-html.test.ts.snap
packages/jsx-directive/tests/fixtures/v-html/v-html.tsx
packages/jsx-directive/tests/fixtures/v-html/v-html.vue
packages/jsx-directive/tests/v-for.test.ts
packages/jsx-directive/tests/v-html.test.ts
packages/jsx-directive/tests/v-if.test.ts
packages/jsx-directive/tests/v-memo.test.ts
playground/vue2/src/App.vue
playground/vue2/src/examples/jsx-directive/index.vue
playground/vue2/src/examples/jsx-directive/v-for.vue
playground/vue2/src/examples/jsx-directive/v-html.vue
playground/vue2/src/examples/jsx-directive/v-if.vue
playground/vue3/src/examples/jsx-directive/v-for.vue
playground/vue3/src/examples/jsx-directive/v-html.vue

Add v-html directive, support vue2 & vue3.

feat(jsx-directive): add v-html directive

---

.changeset/fresh-zoos-marry.md
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-memo.ts
packages/jsx-directive/tests/__snapshots__/v-for.test.ts.snap
packages/jsx-directive/tests/__snapshots__/v-memo.test.ts.snap
packages/jsx-directive/tests/fixtures/v-for/v-for.vue
packages/volar/src/jsx-directive.ts

feat(jsx-directive): v-for directive supports Map and Set

---

.changeset/grumpy-cheetahs-watch.md
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-memo.ts
packages/jsx-directive/tests/__snapshots__/v-for.test.ts.snap
packages/jsx-directive/tests/__snapshots__/v-memo.test.ts.snap
packages/jsx-directive/tests/fixtures/v-for/v-for.vue
packages/volar/src/jsx-directive.ts

feat(jsx-directive): v-for supports Integer, Object and Iterable Object

---

.changeset/light-beans-smile.md
packages/define-prop/src/core/index.ts
playground/vue3/src/examples/define-prop/child.vue

``` ts
const foo = $(defineProp())
```

feat(define-prop): used with reactivity transform

---

.changeset/four-cheetahs-clap.md
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-html.ts
packages/jsx-directive/src/core/v-if.ts
packages/jsx-directive/src/core/v-memo.ts
packages/jsx-directive/src/core/v-slot.ts
playground/vue2/src/examples/jsx-directive/v-for.vue
playground/vue2/src/examples/jsx-directive/v-html.vue
playground/vue3/src/examples/jsx-directive/v-for.vue
playground/vue3/src/examples/jsx-directive/v-html.vue

https://vuejs.org/api/built-in-special-elements.html#template

feat(jsx-directive): converts the template tag to an empty tag

---

.changeset/slow-rabbits-yell.md
packages/volar/src/common.ts
packages/volar/src/define-models.ts
packages/volar/src/export-expose.ts

Fixed volar plugins: 
`exportExpose` `exportProps` `defineModels`

fix(volar): compatible with volar@1.8.14

---

docs/.vitepress/configs/pwa.ts
docs/vercel.json
docs/vite.config.ts

Enable `selfDestroying` in PWA

refactor(docs): remove pwa

---

docs/.vitepress/theme/style.css

fix(docs): brand button text color

---

docs/.vitepress/configs/locale.ts
docs/.vitepress/i18n/locales.ts
docs/interactive/InteractiveDemo.vue
docs/interactive/InteractiveWrapper.vue
docs/interactive/index.md
docs/interactive/logic.ts
docs/package.json
docs/zh-CN/interactive/index.md
pnpm-lock.yaml

**Help wanted: UI should be improved** /cc @Innei @zhiyuanzmj 
Visit: https://vue-macros-git-feat-interactive-example-vuejs.vercel.app/interactive/
Current UI:

feat(docs): interactive docs

---

docs/zh-CN/macros/define-prop.md

Translated the documentation for `defineProp`
I may not be able to guarantee that my translation is correct, so if you can I hope you can see if there is something wrong with it.

docs: add zh-CN docs for defineProp

---

docs/interactive/InteractiveDemo.vue

I felt that the previous Interactive Example was a bit skimpy, so I thought I'd add a bit of style to it,the style references the VueUse.
Modify the style of Interactive Example,The modified style is as follows:

feat(docs): improve style of Interactive Example

---

docs/zh-CN/macros/define-emit.md

Translated the documentation for `defineEmit`

docs: add zh-CN docs for defineEmit

---

docs/macros/setup-sfc.md
docs/zh-CN/macros/setup-sfc.md

https://vue-macros.dev/macros/setup-sfc.html

docs(setup-sfc): move vue to plugins

---

docs/guide/getting-started.md
docs/zh-CN/guide/getting-started.md

docs: add @vue-macros/cli

---

.changeset/silent-windows-punch.md
packages/jsx-directive/src/core/v-on.ts

Add a semicolon at the end of transformVOn.

fix(jsx-directive/v-on): resolve conflicts with `unplugin-auto-import`

---

.changeset/popular-rivers-itch.md
packages/api/src/vue/emits.ts
packages/better-define/tests/__snapshots__/fixtures.test.ts.snap
packages/better-define/tests/fixtures/short-emits.vue
playground/vue3/src/examples/better-define/index.vue
playground/vue3/src/examples/better-define/short-emits.vue

feat(better-define): support `short-emits` syntax

---

.changeset/lovely-poets-hug.md
.changeset/seven-icons-fold.md
packages/volar/src/common.ts
packages/volar/src/define-models.ts
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-on.ts
packages/volar/src/jsx-directive/v-slot.ts
playground/vue3/src/examples/jsx-directive/v-model/child.vue
playground/vue3/src/examples/jsx-directive/v-model/index.vue

feat(volar/jsx-directive): support type for v-model

---

.changeset/hungry-dingos-add.md
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-html.ts
packages/jsx-directive/src/core/v-if.ts
packages/jsx-directive/src/core/v-memo.ts
packages/jsx-directive/src/core/v-on.ts
packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/jsx-directive/tests/fixtures/v-slot/child.vue
packages/jsx-directive/tests/fixtures/v-slot/index.vue
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/v-for.ts
packages/volar/src/jsx-directive/v-if.ts
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-on.ts
packages/volar/src/jsx-directive/v-slot.ts

refactor(jsx-directive/v-slot): v-slot and v-if co-usage

---

.changeset/early-zoos-leave.md
packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/jsx-directive/tests/fixtures/v-slot/child.vue
packages/jsx-directive/tests/fixtures/v-slot/index.vue
packages/volar/src/jsx-directive/v-slot.ts

fix(jsx-directive/v-slot): `default slot` and `v-if slot` co-usage

---

.changeset/beige-hounds-carry.md
docs/features/jsx-directive.md
docs/zh-CN/features/jsx-directive.md
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/v-on.ts
packages/jsx-directive/tests/__snapshots__/v-on.test.ts.snap
packages/jsx-directive/tests/fixtures/v-on/child.vue
packages/jsx-directive/tests/fixtures/v-on/index.vue
packages/jsx-directive/tests/v-on.test.ts
packages/volar/src/jsx-directive.ts
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/v-on.ts
packages/volar/src/jsx-directive/v-slot.ts
playground/vue2/src/examples/jsx-directive/index.vue
playground/vue2/src/examples/jsx-directive/v-on/child.vue
playground/vue2/src/examples/jsx-directive/v-on/index.vue
playground/vue2/src/examples/jsx-directive/v-slot/child.vue
playground/vue2/src/examples/jsx-directive/v-slot/index.vue
playground/vue3/src/examples/jsx-directive/index.vue
playground/vue3/src/examples/jsx-directive/v-on/child.vue
playground/vue3/src/examples/jsx-directive/v-on/index.vue
playground/vue3/src/examples/jsx-directive/v-slot/index.vue

```tsx
<form onSubmit_prevent onClick_capture_stop={() => {}}>
...
</form>
```

feat(jsx-directive/v-on): support modifiers

---

.changeset/famous-kings-own.md
packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/jsx-directive/tests/fixtures/v-slot/child.vue
packages/jsx-directive/tests/fixtures/v-slot/index.vue
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/v-bind.ts
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-on.ts
packages/volar/src/jsx-directive/v-slot.ts

Supports: `prop` `v-on` `v-model` `v-slot`

feat(volar/jsx-directive): convert kebabCase to camelCase

---

.changeset/sixty-terms-sleep.md
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/v-bind.ts

fix(volar/jsx-directive): support kebabCase for prop

---

.changeset/gold-pets-mix.md
packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/jsx-directive/tests/fixtures/v-slot/child.vue
packages/jsx-directive/tests/fixtures/v-slot/index.vue
packages/volar/src/jsx-directive/v-bind.ts
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-on.ts
packages/volar/src/jsx-directive/v-slot.ts

revert(jsx-directive): prevent convert `v-on` & `v-slot` to camelCase

---

.changeset/flat-candles-fail.md
packages/volar/src/common.ts
packages/volar/src/jsx-directive/v-model.ts
playground/vue3/src/examples/jsx-directive/v-model/child.vue
playground/vue3/src/examples/jsx-directive/v-model/index.vue

```tsx
<Comp v-model={[foo, 'bar', ['number']]} />
```

feat(volar/jsx-directive): support dynamic argument for v-model

---

.changeset/beige-frogs-work.md
packages/jsx-directive/src/index.ts

feat(jsx-directive): support .jsx suffix by default

---

.changeset/rotten-snakes-rhyme.md
packages/volar/src/jsx-directive/v-slot.ts

fix(jsx-directive/volar):  support jsxSelfClosingElement in v-slot

---

.changeset/sharp-elephants-dress.md
packages/export-expose/tests/__snapshots__/fixtures.test.ts.snap
packages/export-expose/tests/fixtures/basic.vue
packages/export-expose/tests/fixtures/rename.vue
packages/volar/src/export-expose.ts
tsconfig.fixture.json

 feat(volar/export-expose): support export `function` & `class` & `module`

---

.changeset/lovely-spoons-cheer.md
packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/volar/src/jsx-directive/v-slot.ts

fix(jsx-directive/v-slot): dynamic slot and named slot co-usage

---

.changeset/polite-paws-doubt.md
packages/jsx-directive/tests/__snapshots__/v-on.test.ts.snap
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/jsx-directive/tests/fixtures/v-on/child.vue
packages/jsx-directive/tests/fixtures/v-on/index.vue
packages/jsx-directive/tests/fixtures/v-slot/child.vue
packages/jsx-directive/tests/fixtures/v-slot/index.vue
packages/volar/src/common.ts
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/v-bind.ts
packages/volar/src/jsx-directive/v-for.ts
packages/volar/src/jsx-directive/v-if.ts
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-on.ts
packages/volar/src/jsx-directive/v-slot.ts

feat(volar/jsx-directive): support generic component 

---

.changeset/loud-otters-speak.md

feat!(volar): upgrade to volar 2

---

.changeset/brown-clouds-check.md
packages/volar/src/jsx-directive/index.ts
playground/vue3/src/examples/jsx-directive/v-slot/index.vue

feat(volar/jsx-directive): support generic component

---

.changeset/modern-dancers-explode.md
packages/volar/src/common.ts
packages/volar/src/export-expose.ts
packages/volar/src/jsx-directive/context.ts
playground/vue3/src/examples/export-expose/child-generic.vue
playground/vue3/src/examples/export-expose/index.vue
playground/vue3/src/vite-env.d.ts

feat(volar/export-expose): support generic component

---

.changeset/lazy-dolphins-relax.md
packages/volar/src/common.ts
packages/volar/src/define-models.ts
packages/volar/src/export-props.ts
playground/vue3/src/examples/define-models/reactivity-transform/child.vue

feat(volar/define-models): support generic component

---

.changeset/serious-pigs-suffer.md
docs/macros/define-emit.md
docs/zh-CN/macros/define-emit.md
packages/define-emit/tests/__snapshots__/fixtures.test.ts.snap
packages/define-emit/tests/fixtures/define-emit.vue
packages/volar/src/define-emit.ts
playground/vue3/src/examples/define-emit/child.vue
playground/vue3/src/examples/define-emit/index.vue
playground/vue3/tsconfig.json
tsconfig.fixture.json

feat(volar): add define-emit plugin

---

.changeset/fuzzy-walls-rule.md

fix(volar/define-prop): $defineProp and defineSlots co-usage

---

.changeset/rude-bags-work.md
packages/export-expose/tests/__snapshots__/fixtures.test.ts.snap
packages/export-expose/tests/fixtures/basic.vue
packages/volar/src/export-expose.ts

fix(volar/export-expose): add prefix semicolon to fix syntax errors

---

packages/volar/src/common.ts

fix(volar): add await before the import function

---

.changeset/shaggy-cougars-film.md
packages/jsx-directive/src/core/v-on.ts
packages/jsx-directive/tests/__snapshots__/v-on.test.ts.snap
packages/jsx-directive/tests/fixtures/v-on/child.vue

```tsx
<input onKeydown_left  />
```

feat(volar/jsx-directive): support keyboard event with keys

---

.changeset/neat-teachers-greet.md
packages/jsx-directive/tests/__snapshots__/v-on.test.ts.snap
packages/jsx-directive/tests/fixtures/v-on/child.vue
packages/jsx-directive/tests/fixtures/v-on/index.vue
packages/volar/src/jsx-directive/v-on.ts

```tsx
<input
onKeydown_down={() => {}}
onKeydown_up={() =>{}}
/>
```
Will be convert to
```tsx
<input
{...{onKeydown: () => {}}}
{...{onKeydown: () => {}}}
/>
```

feat(volar/jsx-directive): allow duplicate events with modifiers

---

.changeset/ten-onions-sniff.md
packages/volar/src/jsx-directive/index.ts

feat(volar/jsx-directive): remove camelCase events support

---

.changeset/tiny-pans-invent.md
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/v-slot.ts

feat(volar/jsx-directive): support type hint for v-slots

---

.changeset/brave-dragons-whisper.md
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/v-slot.ts

feat(volar/jsx-directive): support slots type hint for object expression

---

.changeset/chilled-cameras-provide.md
packages/common/src/dep.ts
packages/define-render/src/core/index.ts
packages/define-render/src/index.ts

feat(define-render): disabled auto-wrapping function when in vapor mode

---

.changeset/flat-vans-push.md
packages/volar/index.d.ts
packages/volar/src/define-emit.ts
packages/volar/src/template-ref.ts
playground/vue3/src/examples/template-ref/child.vue
playground/vue3/src/examples/template-ref/index.vue
playground/vue3/tsconfig.json

feat(volar): introduce template-ref

---

docs/.vitepress/locale.ts
docs/volar/setup-jsdoc.md
docs/zh-CN/volar/setup-jsdoc.md

docs: add setupJSDoc

---

packages/macros/package.json
packages/macros/src/config-worker.ts
packages/macros/src/config.ts
packages/macros/src/index.ts
packages/macros/tsup.config.ts
playground/vue3/package.json
playground/vue3/rollup.config.js
playground/vue3/vite.config.ts
playground/vue3/vue-macros.config.ts
pnpm-lock.yaml

feat(macros): load config file

---

.changeset/gorgeous-balloons-kiss.md
packages/volar/src/setup-sfc.ts

fix(volar/setup-sfc): auto imports not working

---

.changeset/many-coins-refuse.md
docs/guide/bundler-integration.md
docs/zh-CN/guide/bundler-integration.md
packages/common/src/constants.ts
packages/config/src/options.ts
packages/macros/src/index.ts

feat: setup-sfc and unplugin-vue-router co-usage

---

.changeset/soft-dryers-tell.md
docs/.vitepress/locale.ts
docs/volar/script-sfc.md
docs/zh-CN/volar/define-generic.md
docs/zh-CN/volar/script-sfc.md
packages/config/src/options.ts
packages/volar/package.json
packages/volar/src/common.ts
packages/volar/src/index.ts
packages/volar/src/script-sfc.ts
packages/volar/src/setup-sfc.ts
playground/vue3/src/examples/script-sfc/index.tsx
playground/vue3/vue-macros.config.ts

feat(volar): introduce script-sfc

---

.changeset/blue-tomatoes-marry.md

feat(config): add script-sfc option

---

.changeset/gorgeous-snails-help.md
packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/volar/src/jsx-directive.ts
packages/volar/src/jsx-directive/context.ts
packages/volar/src/jsx-directive/v-slot.ts

feat(jsx-directive): use vSlots prop as component's slots

---

.changeset/real-trees-retire.md
packages/volar/src/boolean-prop.ts
packages/volar/src/common.ts
packages/volar/src/define-emit.ts
packages/volar/src/define-generic.ts
packages/volar/src/define-models.ts
packages/volar/src/define-options.ts
packages/volar/src/define-prop.ts
packages/volar/src/define-props-refs.ts
packages/volar/src/define-props.ts
packages/volar/src/define-slots.ts
packages/volar/src/export-expose.ts
packages/volar/src/export-props.ts
packages/volar/src/export-render.ts
packages/volar/src/index.ts
packages/volar/src/jsx-directive.ts
packages/volar/src/script-lang.ts
packages/volar/src/script-sfc.ts
packages/volar/src/setup-jsdoc.ts
packages/volar/src/setup-sfc.ts
packages/volar/src/short-bind.ts
packages/volar/src/short-vmodel.ts
packages/volar/src/template-ref.ts

You don't need to manually enable it.
```ts
"vueCompilerOptions": {
"plugins": ["@vue-macros/volar/script-sfc"],
},
```

feat(volar): compatible with old usage

---

docs/.vitepress/theme/Layout.vue
package.json
packages/volar/src/export-expose.ts
playground/vue2/package.json
playground/vue3/package.json
pnpm-lock.yaml
pnpm-workspace.yaml
tsconfig.lib.json
tsup.config.ts

feat: enable `noCheck` for dts

---

docs/.vitepress/components/HomePage.vue

Fixed Moblie CSS style
No issue

fix(docs): wrap team members on small screen

---

.changeset/grumpy-toes-tell.md
packages/jsx-directive/src/index.ts
playground/nuxt/examples/jsx-directive/v-for.vue

feat(jsx-directive): set `enforce` to pre

---

.changeset/curly-flies-repair.md
packages/volar/src/jsx-directive/v-for.ts
packages/volar/src/jsx-directive/v-if.ts
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-slot.ts

feat(volar/jsx-directive): add event-prop for v-model

---

.changeset/tough-moose-kick.md
packages/define-prop/tests/__snapshots__/fixtures.test.ts.snap
packages/define-prop/tests/fixtures/johnson-edition/basic.vue
packages/volar/src/define-prop.ts

fix(volar): remove duplicate __VLS_PropOptions type

---

.changeset/sharp-hats-confess.md
packages/volar/src/jsx-directive/context.ts
packages/volar/src/jsx-directive/index.ts

feat(volar/jsx-directive): support functional component

---

docs/.vitepress/config/theme.ts
docs/volar/jsx-ref.md
docs/vue-macros.config.ts
docs/zh-CN/volar/define-generic.md
docs/zh-CN/volar/jsx-ref.md

docs: add jsx-ref

---

.changeset/light-pumpkins-remember.md
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-slot.ts

fix(volar/jsx-directive): v-model and v-slot co-usage

---

packages/macros/macros-global.d.ts

fix(macros): nuxt define-prop type error

---

.changeset/brave-rules-beam.md
packages/volar/src/jsx-directive/context.ts

feat(volar/jsx-directive): support elementAccessExpression for ref

---

packages/volar/src/index.ts
packages/volar/src/jsx-directive.ts
packages/volar/src/jsx-ref.ts

fix(volar): support options for ts-macro plugins

---

.changeset/soft-nails-cheer.md
packages/volar/src/jsx-directive/custom-directive.ts
packages/volar/src/jsx-directive/index.ts
playground/vue3/src/examples/jsx-directive/custom-directive.vue

feat(volar/jsx-directive): support custom-directive

---

docs/macros/define-props-refs.md
docs/zh-CN/macros/define-props-refs.md

docs: fix define-props-refs usage

---

.changeset/old-trees-leave.md
packages/define-slots/macros.d.ts

feat(define-slots): return generic to support Vue 3.2

---

packages/volar/src/define-prop.ts

Fix that name was not retrieved using JohnsonEdition

fix(volar/define-prop): get identifier name correctly

---

.changeset/tender-ligers-wave.md
packages/volar/src/define-emit.ts
packages/volar/src/define-prop.ts
packages/volar/src/jsx-ref.ts

feat(volar): get identifier name correctly

---

.changeset/tricky-readers-judge.md
packages/volar/src/jsx-directive/custom-directive.ts
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/ref.ts
packages/volar/src/jsx-directive/v-for.ts
packages/volar/src/jsx-directive/v-if.ts
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-on.ts
packages/volar/src/jsx-directive/v-slot.ts
packages/volar/src/jsx-ref.ts

refactor(volar): use ts-macro instead of @vue/language-core for jsx-plugins

---

.changeset/seven-beans-exercise.md
packages/jsx-directive/package.json
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/restructure/helper.ts
packages/jsx-directive/src/core/restructure/index.ts
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/src/helpers.ts
packages/jsx-directive/tests/__snapshots__/restructure.test.ts.snap
packages/jsx-directive/tests/__snapshots__/v-for.test.ts.snap
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/jsx-directive/tests/fixtures/v-for/index.vue
packages/jsx-directive/tests/restructure.test.ts
packages/jsx-directive/tests/v-slot.test.ts
pnpm-lock.yaml

feat(jsx-directive): support restructure v-for and v-slot for vue/vapor

---

.changeset/serious-trains-yell.md
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-if.ts
packages/jsx-directive/tests/__snapshots__/v-for.test.ts.snap
packages/jsx-directive/tests/__snapshots__/v-if.test.ts.snap
packages/jsx-directive/tests/fixtures/v-for/index.vue
packages/jsx-directive/tests/fixtures/v-if/v-if.vue

feat(jsx-directive): wrap root JSX elements with Fragment for v-if and v-for

---

.changeset/new-wolves-hope.md
docs/features/jsx-directive.md
docs/zh-CN/features/jsx-directive.md
packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/plugin.ts
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-html.ts
packages/jsx-directive/src/core/v-if.ts
packages/jsx-directive/src/core/v-memo.ts
packages/jsx-directive/src/core/v-model.ts
packages/jsx-directive/src/core/v-on.ts
packages/jsx-directive/src/core/v-slot.ts

refactor(jsx-directive): use lib instead of version for helper imports

---

.changeset/puny-turkeys-watch.md
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/tests/__snapshots__/v-for.test.ts.snap

feat(jsx-directive): support restructure v-for for vapor mode

---

docs/macros/define-prop.md
docs/package.json
docs/zh-CN/macros/define-prop.md
package.json
packages/volar/src/common.ts
pnpm-lock.yaml
pnpm-workspace.yaml

feat: upgrade volar support to `v2.2.4`

---

packages/jsx-directive/src/core/index.ts
packages/jsx-directive/src/core/v-model.ts
packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/src/helpers.ts
packages/jsx-directive/tests/__snapshots__/v-model.test.ts.snap
packages/jsx-directive/tests/fixtures/v-model/index.vue
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-slot.ts

Use `_` instead.
```tsx
const slotName = ref('foo')
<Comp v-slot:$slotName_value$ ></Comp>
```

feat(jsx-directive): remove unref for dynamic argument

---

packages/common/src/ast.ts
packages/define-models/src/core/index.ts
packages/define-prop/src/core/index.ts
packages/jsx-directive/src/core/v-for.ts
packages/jsx-directive/src/core/v-memo.ts
packages/jsx-directive/src/core/v-on.ts
packages/jsx-directive/src/core/v-slot.ts

This is useful to support alias option. Users can customize the macro name they like.
```tsx
defineComponent: {
alias: ['$component']
}
```

feat(common): support `local` option for `importHelperFn`

---

packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/volar/src/jsx-directive/context.ts
packages/volar/src/jsx-directive/v-slot.ts

feat(jsx-directive)!:  use v-slots instead of vSlots

---

packages/volar/src/jsx-directive/v-model.ts

fix(volar/jsx-directive): prevent add events for native input tag

---

packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-slot.ts

fix(volar): remove unused patch code

---

packages/volar/src/jsx-directive/v-model.ts

Relation issue: https://github.com/vuejs/core/pull/13070

fix(volar/jsx-directive): use modelValueModifiers instead of modelModifiers

---

packages/jsx-directive/src/core/v-slot.ts
packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap

Relation issue https://github.com/vuejs/babel-plugin-jsx/issues/712

feat(jsx-directive): add $stable flag for v-slot

---

packages/volar/src/common.ts
packages/volar/src/define-emit.ts
packages/volar/src/define-models.ts
packages/volar/src/define-prop.ts
packages/volar/src/export-props.ts
playground/vue3/src/examples/define-models/runtime/child.vue
playground/vue3/src/examples/define-models/runtime/parent.vue
playground/vue3/vue-macros.config.ts

feat(volar): support __typeProps & __typeEmits for Vue 3.5

---

packages/jsx-directive/tests/__snapshots__/v-for.test.ts.snap
packages/jsx-directive/tests/fixtures/v-for/index.vue
packages/volar/src/jsx-directive/v-for.ts
packages/volar/src/jsx-directive/v-if.ts

fix(volar/jsx-directive): use getStart instead of pos for v-if and v-for

---

packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
packages/jsx-directive/tests/fixtures/v-slot/index.vue
packages/volar/src/jsx-directive/v-slot.ts

fix(volar/jsx-directive): allow dynamic v-slot without expression

---

packages/volar/package.json
packages/volar/src/jsx-directive/context.ts
pnpm-lock.yaml

fix(volar/jsx-directive): prevent generating component context for native elements

---

packages/volar/src/common.ts
packages/volar/src/jsx-directive.ts
packages/volar/src/jsx-directive/context.ts
packages/volar/src/jsx-directive/custom-directive.ts
packages/volar/src/jsx-directive/index.ts
packages/volar/src/jsx-directive/ref.ts
packages/volar/src/jsx-directive/v-bind.ts
packages/volar/src/jsx-directive/v-for.ts
packages/volar/src/jsx-directive/v-if.ts
packages/volar/src/jsx-directive/v-model.ts
packages/volar/src/jsx-directive/v-on.ts
packages/volar/src/jsx-directive/v-slot.ts
packages/volar/src/jsx-ref.ts
pnpm-lock.yaml
pnpm-workspace.yaml

No need `source` and `allCodeFeatures`, will be auto added in codes proxy handler.

refactor(volar): upgrade ts-macro to 0.2.5

---

docs/macros/define-stylex.md
docs/zh-CN/macros/define-stylex.md
packages/define-stylex/src/core/index.ts
packages/define-stylex/tests/__snapshots__/fixtures.test.ts.snap

fix(define-stylex): use props instead of attrs from stylex@^0.13.0

---

packages/volar/src/jsx-directive/context.ts

feat(volar/jsx-directive): support infer type from setup

---

packages/define-stylex/src/core/index.ts
packages/define-stylex/tests/__snapshots__/fixtures.test.ts.snap
packages/define-stylex/tests/fixtures/multiple-statements.vue
packages/define-stylex/tests/fixtures/other-statements.vue

fix(define-stylex): fix unwanted code hoist

---

packages/volar/src/export-expose.ts
pnpm-lock.yaml
pnpm-workspace.yaml

chore: upgrade @vue/language-tools to 3.0.6

---

packages/volar/src/jsx-directive/context.ts

feat(volar/jsx-directive): support VaporInstance

---

packages/volar/src/jsx-directive/context.ts

fix(volar/jsx-directive): use ShallowUnwrapRef for Exposed

---

docs/macros/define-stylex.md
docs/zh-CN/macros/define-stylex.md
packages/define-stylex/macros.d.ts
packages/define-stylex/src/core/helper/index.ts
packages/define-stylex/src/core/helper/stylex-attrs.ts
packages/define-stylex/src/core/index.ts
packages/define-stylex/src/index.ts
packages/define-stylex/tests/__snapshots__/fixtures.test.ts.snap
playground/vue3/package.json
playground/vue3/src/App.vue
playground/vue3/src/main.ts
playground/vue3/vite.config.ts
pnpm-lock.yaml
pnpm-workspace.yaml

fix(define-stylex): use `attrs()` instead of `props()`
